### ISSUE TITLE
UI/UX for User Story: Adding a row and column (ghost row and column)

### ISSUE THREAD

**Issue by ryuntalan** [jupytercalpoly/jupyterlab-tabular-data-editor#113]
## Description
This is an example of a way to add a row or column. With a single click, you can add a new row or column to the end of your data table. So if you were to acquire new information, you can quickly append that data to your table.

![add-row-column](https://user-images.githubusercontent.com/16173670/88575753-328b0780-cff9-11ea-80f7-867b852c4151.gif)
(slight mistake with the prototype: the add row button is supposed to extend when the new column is added)

## Related Issues
None

## Questions
What are the different use cases when using this feature?

Should the add row/ columns be less prominent (more transparent)?

Feedback on this concept would be greatly appreciated!

## Interactive Prototype
[Prototype Link](https://www.figma.com/proto/SLJlzW2DjPPDTTbV64A8bN/Shrimp-n-Grids?node-id=512%3A7138&scaling=min-zoom)

**Comment by kgoo124** [comment]
@ryuntalan I think more transparency would be better as right now it looks like these rows/columns are part of the table. Out of the two different designs, the additional row one makes more sense just from a mental model perspective.

**Comment by lmcnichols** [comment]
I second Kalen's feedback. I would also say both designs are really cool!

**Comment by ryuntalan** [comment]
**Updated Design**

![add-row-column](https://user-images.githubusercontent.com/16173670/89679516-19f6d900-d8a6-11ea-92e1-fdccd4d7b782.gif)
