### ISSUE TITLE
Different cell editors

### ISSUE THREAD

**Issue by kgoo124** [jupytercalpoly/jupyterlab-tabular-data-editor#171]
**Describe the new feature being added**
Based on the type of data within a column, `boolean`, `string`, `number`, `Date`, the cell editor will be changed to reflect that specific type.

**How will this feature improve this extension**
Different cell editors visualize the data better and users have incentive to keep their columns of the same data type

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ryuntalan** [comment]
This is an interesting feature! Is it based on the type of data within a column or within a cell?

Based on how Google Sheets and Excel does alignment: 
- Booleans are aligned centered and are made uppercase
- Strings are aligned left
- Numbers are aligned right
- Dates are aligned left

**Comment by kgoo124** [comment]
@ryuntalan I'm thinking it would be based on columns. Still need to figure the implementation details on that though
