### ISSUE TITLE
Create a new branch on our Forked Jupyterlab repos to serve our @lumino/datagrid package

### ISSUE THREAD

**Issue by lmcnichols** [jupytercalpoly/jupyterlab-tabular-data-editor#18]
The default datagrid has it's `editingEnabled` property set to private (with a value of false). We need to create a package in which this is protected so our extension of the datagrid can set this to true.

**Comment by kgoo124** [comment]
Not necessary at this time
Able to just set the `editingEnabled` property to `true` via a setter method
