### ISSUE TITLE
JupyterLab 3.0 support?

### ISSUE THREAD

**Issue by krassowski** [jupytercalpoly/jupyterlab-tabular-data-editor#316]
Hi, JupyterLab 3.0 has been released recently and it would be very nice to see your extension ported. There is an automated script that can help to get you started: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

I really hope to see the version 1.0 soon :)

**Comment by pressla** [comment]
Conflicting Dependencies:
JupyterLab                 Extension      Package
>=3.0.4 <3.1.0             >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.3 <3.1.0             >=2.2.0 <3.0.0 @jupyterlab/apputils
>=5.0.2 <5.1.0             >=4.2.0 <5.0.0 @jupyterlab/coreutils
>=3.0.4 <3.1.0             >=2.2.0 <3.0.0 @jupyterlab/documentsearch
>=3.0.3 <3.1.0             >=2.2.2 <3.0.0 @jupyterlab/launcher
>=3.0.3 <3.1.0             >=2.1.1 <3.0.0 @jupyterlab/mainmenu
>=6.0.3 <6.1.0             >=5.2.1 <6.0.0 @jupyterlab/services

are there plans to make a version?

**Comment by krassowski** [comment]
I tried upgrading to JupyterLab 3, but the mysterious dependency on tde-csvviewer is hardcoded to use `"@jupyterlab/apputils" "^2.2.0"` among others. It looks like a fork of @jupyterlab/csvviewer but re-uploaded here: https://www.npmjs.com/package/tde-csvviewer . Sadly the GitHub linked repo (github.com/lomcnich/jupyterlab) does not exist so I do not even know how to send a PR there to upgrade it - CC @loganamcnichols. It would be also useful to know why it was forked in the first place.

**Comment by krassowski** [comment]
Okay, I updated my https://github.com/krassowski/jupyterlab-spreadsheet-editor to support JupyterLab 3.0 in the meantime, just in case if anyone is being held off with upgrading to JupyterLab 3.0 due to a need for tabular data editor (and because I needed it for my day job).

**Comment by lmcnichols** [comment]
Thanks for the message Krassowski.

I know that we created those tde packages because we needed slight modifications to the @lumino & @jupyterlab packages. Meanwhile, we were submitting PR's to @lumino and @jupyterlab packages to get those changes implemented. If I recall correctly we were able to get all the changes we wanted in to @lumino and @jupyterlab before the internship ended. There was a further issue though that @jupyterlab doesn't immediately implement the latest versions of the @lumino packages, so the extension still required our modified packages. Maybe by now they could all be swapped out with the main ones.

**Comment by krassowski** [comment]
Thanks for the quick reply @lmcnichols. I sent a PR which brings JupyterLab compatibility swapping all tde-* packages with most recent versions of appropriate lumino or jupyterlab packages. It does work, but it is possible that some improvements (especially visual ones) that you had on the forks are missing.

I would recommend the team of authors to check the update for regressions and if you discover that any more changes need to be up-streamed to PR those changes now, while you still have those in the recent memory. Please feel free to tag me for review/advocating for you in the upstream jupyterlab repositories if needed.
