### ISSUE TITLE
Uploading to PYPI

### ISSUE THREAD

**Issue by kartheekgottipati** [jupytercalpoly/jupyterlab-tabular-data-editor#318]
Now there is support for jupyterlab3 and it is available as a python package is there a plan to upload it to PYPI?

**Comment by kartheekgottipati** [comment]
Packaged and uploaded to PYPI.

**Comment by krassowski** [comment]
Hi @kartheekgottipati, thank you for the suggestion. Could you please transfer the PyPI package to me so that I can set-up automated publish script (assuming that the maintainers here agree, CC @jupytercalpoly).

**Comment by kartheekgottipati** [comment]
> Hi @kartheekgottipati, thank you for the suggestion. Could you please transfer the PyPI package to me so that I can set-up automated publish script (assuming that the maintainers here agree, CC @jupytercalpoly).

Do you have PYPI user id?

**Comment by krassowski** [comment]
https://pypi.org/user/krassowski/

**Comment by kartheekgottipati** [comment]
Invited. Once you accept the invite i will remove owner role.

**Comment by krassowski** [comment]
Thank you, I got.
